name: SkyBound
main: SkyBoundPlugin
version: ${pom.version}
author: phit
commands:
  island:
    aliases: is
permissions:    
  skybound.*:
    children:
      skybound.island.*:
        children:
          skybound.island.create:
            description: Allows the player to create a new island
      skybound.tp.*:
        children:
          skybound.tp.home:
            description: Allows the player to teleport to their island
          skybound.tp.spawn:
            description: Allows the player to teleport to the main world
      skybound.party.*:
        children:
          skybound.party.invite:
            description: Allows the player to invite other players
          skybound.party.kick:
            description: Allows the player to kick other players
          skybound.party.promote:
            description: Allows the player to change the leader of their party
          skybound.party.accept:
            description: Allows the player to accept an invite
          skybound.party.decline:
            description: Allows the player to decline an invite
          skybound.party.leave:
            description: Allows the player to leave their party
          skybound.party.leader:
            description: Allows the player to view their party's leader
          skybound.party.members:
            description: Allows the player to view their party's members
      skybound.admin.*:
        children:
          skybound.admin.destroy:
            description: Allows the player to destroy another player's island
          skybound.admin.tp:
            description: Allows the player to teleport to another players's island